import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo } from 'react';
import { translations, getDaftarJabatan, getJabatanLabel } from '../constants/translations';
export const KaryawanTable = ({ data, lang, searchTerm, onDelete, }) => {
    const daftarJabatan = getDaftarJabatan(lang);
    const filteredData = useMemo(() => {
        return data.filter((k) => k.nama.toLowerCase().includes(searchTerm.toLowerCase()));
    }, [data, searchTerm]);
    return (_jsxs("div", { className: "bg-white p-8 rounded-[2.5rem] border border-slate-100 lg:col-span-2 shadow-sm relative overflow-hidden flex flex-col h-[500px]", children: [_jsx("div", { className: "absolute top-0 left-0 w-1 h-full bg-indigo-400" }), _jsx("div", { className: "flex justify-between items-center mb-6", children: _jsxs("div", { className: "flex flex-col", children: [_jsx("h2", { className: "text-xl font-black uppercase italic text-slate-900", children: translations[lang].listTitle }), _jsxs("span", { className: "text-[10px] font-black text-indigo-400 uppercase italic", children: [data.length, " ", translations[lang].members] })] }) }), _jsx("div", { className: "overflow-y-auto pr-2 custom-scrollbar", children: _jsxs("table", { className: "w-full text-left border-separate border-spacing-y-3", children: [_jsx("thead", { className: "sticky top-0 bg-white z-10", children: _jsxs("tr", { className: "text-[9px] text-slate-400 font-black uppercase tracking-widest", children: [_jsx("th", { className: "pb-4 pl-4", children: translations[lang].colName }), _jsx("th", { className: "pb-4 text-center", children: translations[lang].colJabatan }), _jsx("th", { className: "pb-4 text-center", children: "PIN" }), _jsx("th", { className: "pb-4 text-center", children: translations[lang].colShift }), _jsx("th", { className: "pb-4 text-right pr-4", children: translations[lang].colOpt })] }) }), _jsx("tbody", { children: filteredData.map((k) => (_jsxs("tr", { className: "bg-slate-50/50 hover:bg-slate-50 transition-all", children: [_jsx("td", { className: "py-4 pl-4 rounded-l-2xl font-black text-xs uppercase italic text-slate-700", children: k.nama }), _jsx("td", { className: "py-4 text-center text-[9px] font-black text-indigo-400 uppercase italic", children: getJabatanLabel(lang, k.jabatan) }), _jsx("td", { className: "py-4 text-center font-mono text-indigo-600 font-bold tracking-widest text-xs", children: k.pin }), _jsx("td", { className: "py-4 text-center", children: _jsx("span", { className: "text-[9px] font-bold bg-white border border-slate-200 px-2 py-1 rounded-lg uppercase", children: k.shift === 'Siang' ? translations[lang].shiftSiang : translations[lang].shiftMalam }) }), _jsx("td", { className: "py-4 text-right pr-4 rounded-r-2xl", children: _jsx("button", { onClick: () => onDelete(k.id, k.nama), className: "text-rose-400 hover:text-rose-600 p-2 transition-all active:scale-90", children: _jsx("svg", { className: "w-4 h-4", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" }) }) }) })] }, k.id))) })] }) }), _jsx("style", { children: `.custom-scrollbar::-webkit-scrollbar { width: 4px; } .custom-scrollbar::-webkit-scrollbar-thumb { background: #E2E8F0; border-radius: 20px; }` })] }));
};
